#!/bin/bash
set -euo pipefail

# compile-rules.sh — Generates references/compiled-rules.md from individual rule files
#
# Usage: bash scripts/compile-rules.sh
#
# Reads:
#   assets/authoring/sections.md   — section ordering and metadata
#   assets/metadata.json           — version, abstract, references
#   references/rules/{prefix}-*.md — individual rule files
#
# Writes:
#   references/compiled-rules.md   — the compiled output (gitignored)
#
# Outputs JSON summary to stdout.

SKILL_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RULES_DIR="$SKILL_ROOT/references/rules"
SECTIONS_FILE="$SKILL_ROOT/assets/authoring/sections.md"
METADATA_FILE="$SKILL_ROOT/assets/metadata.json"
OUTPUT_FILE="$SKILL_ROOT/references/compiled-rules.md"

# ── Read metadata via jq ────────────────────────────────────────────────────

VERSION=$(jq -r '.version' "$METADATA_FILE")
ORG=$(jq -r '.organization' "$METADATA_FILE")
DATE=$(jq -r '.date' "$METADATA_FILE")
ABSTRACT=$(jq -r '.abstract' "$METADATA_FILE")

# ── Parse sections from sections.md ─────────────────────────────────────────
#
# Format per section block:
#   ## N. Name (prefix)
#   **Impact:** LEVEL
#   **Description:** multi-line text...

declare -a SECT_NUMS=() SECT_NAMES=() SECT_PREFIXES=() SECT_IMPACTS=() SECT_DESCS=()

idx=-1
collecting_desc=false

while IFS= read -r line; do
  if [[ "$line" =~ ^##\ ([0-9]+)\.\ (.+)\ \(([a-z]+)\)$ ]]; then
    idx=$((idx + 1))
    SECT_NUMS+=("${BASH_REMATCH[1]}")
    SECT_NAMES+=("${BASH_REMATCH[2]}")
    SECT_PREFIXES+=("${BASH_REMATCH[3]}")
    SECT_IMPACTS+=("")
    SECT_DESCS+=("")
    collecting_desc=false
  elif [[ $idx -ge 0 && "$line" =~ ^\*\*Impact:\*\*\ (.+) ]]; then
    raw="${BASH_REMATCH[1]}"
    SECT_IMPACTS[$idx]=$(echo "$raw" | sed 's/[[:space:]]*$//')
  elif [[ $idx -ge 0 && "$line" =~ ^\*\*Description:\*\*\ (.+) ]]; then
    SECT_DESCS[$idx]="${BASH_REMATCH[1]}"
    collecting_desc=true
  elif [[ $idx -ge 0 && "$collecting_desc" == "true" && -n "$line" ]]; then
    SECT_DESCS[$idx]="${SECT_DESCS[$idx]}
$line"
  else
    collecting_desc=false
  fi
done < "$SECTIONS_FILE"

total_sections=${#SECT_NUMS[@]}

# ── Helpers ──────────────────────────────────────────────────────────────────

# Generate a GitHub-compatible markdown anchor from heading text.
to_anchor() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9 -]//g; s/ /-/g; s/^-//; s/-$//'
}

# Extract the display title from the first ## heading after YAML frontmatter.
extract_title() {
  awk '
    BEGIN { fm = 0 }
    /^---$/ { fm++; next }
    fm >= 2 && /^## / { sub(/^## */, ""); print; exit }
  ' "$1"
}

# Extract body content: strip frontmatter, strip first ## heading,
# trim leading/trailing blanks, strip trailing "Reference: ..." line.
extract_body() {
  awk '
    BEGIN { fm = 0; skipped = 0 }
    /^---$/ { fm++; next }
    fm < 2 { next }
    !skipped && /^## / { skipped = 1; next }
    { lines[++n] = $0 }
    END {
      s = 1
      while (s <= n && lines[s] ~ /^[[:space:]]*$/) s++
      while (n >= s && lines[n] ~ /^[[:space:]]*$/) n--
      if (n >= s && lines[n] ~ /^Reference:/) n--
      while (n >= s && lines[n] ~ /^[[:space:]]*$/) n--
      for (i = s; i <= n; i++) print lines[i]
    }
  ' "$1"
}

# ── Build output ─────────────────────────────────────────────────────────────

{
  # ── Auto-generated marker ──
  echo "<!-- AUTO-GENERATED by scripts/compile-rules.sh — DO NOT EDIT -->"
  echo ""

  # ── Header ──
  echo "# Nx TypeScript Workspace"
  echo ""
  echo "**Version ${VERSION}**"
  echo "${ORG}"
  echo "${DATE}"
  echo ""
  cat <<'STATIC_NOTE'
> **Note:**
> This document is mainly for agents and LLMs to follow when maintaining,
> generating, or refactoring code in Nx TypeScript monorepo workspaces. Humans
> may also find it useful, but guidance here is optimized for automation
> and consistency by AI-assisted workflows.

---
STATIC_NOTE
  echo ""

  # ── Abstract ──
  echo "## Abstract"
  echo ""
  echo "${ABSTRACT}"
  echo ""
  echo "---"
  echo ""

  # ── Table of Contents ──
  echo "## Table of Contents"
  echo ""

  for ((s = 0; s < total_sections; s++)); do
    num="${SECT_NUMS[$s]}"
    name="${SECT_NAMES[$s]}"
    prefix="${SECT_PREFIXES[$s]}"
    impact="${SECT_IMPACTS[$s]}"

    section_anchor=$(to_anchor "$num. $name")
    echo "$num. [$name](#$section_anchor) — **$impact**"

    rule_idx=0
    for rule_file in "$RULES_DIR/${prefix}"-*.md; do
      [ -f "$rule_file" ] || continue
      rule_idx=$((rule_idx + 1))
      title=$(extract_title "$rule_file")
      rule_anchor=$(to_anchor "$num.$rule_idx $title")
      echo "   - $num.$rule_idx [$title](#$rule_anchor)"
    done
  done

  echo ""
  echo "---"
  echo ""

  # ── Sections and rules ──
  total_rules=0

  for ((s = 0; s < total_sections; s++)); do
    num="${SECT_NUMS[$s]}"
    name="${SECT_NAMES[$s]}"
    prefix="${SECT_PREFIXES[$s]}"
    impact="${SECT_IMPACTS[$s]}"
    desc="${SECT_DESCS[$s]}"

    echo "## $num. $name"
    echo ""
    echo "**Impact: $impact**"
    echo ""
    echo "$desc"
    echo ""

    rule_idx=0
    for rule_file in "$RULES_DIR/${prefix}"-*.md; do
      [ -f "$rule_file" ] || continue
      rule_idx=$((rule_idx + 1))
      total_rules=$((total_rules + 1))
      title=$(extract_title "$rule_file")

      echo "### $num.$rule_idx $title"
      echo ""
      extract_body "$rule_file"
      echo ""
    done

    echo "---"
    echo ""
  done

  # ── References footer ──
  echo "## References"
  echo ""
  jq -r '.references | to_entries[] | "\(.key + 1). [\(.value.title)](\(.value.url))"' "$METADATA_FILE"

} > "$OUTPUT_FILE"

output_lines=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')

# ── JSON summary to stdout ──
printf '{"sections":%d,"rules":%d,"outputLines":%s}\n' \
  "$total_sections" "$total_rules" "$output_lines"
